### ISSUE TITLE
[REQ] Filter by ratings

### ISSUE THREAD

**Issue by vahtos** [giuseppe99barchetta/SuggestArr#72]
Related to #57. It would be great if there was a way to apply more rules to what is requested. For example, filtering by rating would be very useful. Kind of like what [Overcrawlerr](https://github.com/psyko-gh/overcrawlrr) does.

Ideally, this would include ratings from various sources (Rotten Tomatoes, TMDB, Trakt, IMDB, etc.), but the easiest to implement is probably TMDB considering the existing integration. It should also consider how many review/votes were aggregated to form that score.

A couple of things that would need to be considered:

- What if the review source does not include that show/movie?
  -  Maybe have a setting for each filter of how to handle that (count it as a pass or fail of the filter condition).
- API keys would be needed for each source used.
  - Adjust install instructions
  - Handle case where a rule exists for source which has no API key (avoid this causing an error in the CRON process and preventing other rules applying, or any suggestions from being added)

Example rules as they might appear in `config.yaml`:
```
FILTERS:
    - type: rating
      source: tmdb
      threshold: 75
      minimumVotes: 50
      failOnMissing: true

   -  type: rating   
      source: imdb
      threshold: 7.5
      minimumVotes: 100
      failOnMissing: false
```
